[ENH] Update digest to support latest Nipoppy processing status files
neurobagel/digest pull request #166
Opened 2024-12-13 18:12 UTC by alyssadai

- Closes #29
- Closes #157
- Closes #165
- Closes #153 
- Closes #158

Changes proposed in this pull request:

-
-

## Checklist
_This section is for the PR reviewer_

- [ ] PR has an interpretable title with a prefix (`[ENH]`, `[FIX]`, `[REF]`, `[TST]`, `[CI]`, `[MNT]`, `[INF]`, `[MODEL]`, `[DOC]`) _(see our [Contributing Guidelines](https://neurobagel.org/contributing/CONTRIBUTING#pull-request-guidelines) for more info)_
- [ ] PR links to GitHub issue with mention `Closes #XXXX`
- [ ] Tests pass
- [ ] Checks pass

For new features:
- [ ] Tests have been added

For bug fixes:
- [ ] There is at least one test that would fail under the original bug conditions.

2024-12-13 19:18 UTC, alyssadai commented
Hey @michellewang, requesting your review here on just the digest schema changes as well as text including READMEs and status descriptions. Will tag you on the relevant files/sections under files changed!

2024-12-13 19:19 UTC, alyssadai commented on README.md
please review @michellewang

2024-12-13 19:19 UTC, alyssadai commented on schemas/README.md
please review @michellewang

2024-12-13 19:19 UTC, alyssadai commented on schemas/imaging_digest_schema.json
please review @michellewang

2024-12-13 19:19 UTC, alyssadai commented on schemas/phenotypic_digest_schema.json
please review @michellewang

2024-12-13 19:22 UTC, alyssadai commented on digest/utility.py
>  }
please review @michellewang

2024-12-20 15:13 UTC, michellewang reviewed
@alyssadai let me know if I missed anything!

2024-12-20 15:13 UTC, michellewang commented on schemas/imaging_digest_schema.json
> +            "Description": "Completion status of the pipeline run or step for the subject-session pair. 'SUCCESS': All output files are present. 'FAIL': At least one output file is missing. 'INCOMPLE
`INCOMPLETE` should/will be about the pipeline itself, not a parent pipeline. What you have in `digest/utility.py` is good I think

```suggestion
            "Description": "Completion status of the pipeline run or step for the subject-session pair. 'SUCCESS': All output files are present. 'FAIL': At least one output file is missing. 'INCOMPLETE': Pipeline has not been run for the subject session. 'UNAVAILABLE': Relevant MRI modality for pipeline not available for subject session.",
```

2024-12-20 15:13 UTC, michellewang commented on schemas/imaging_digest_schema.json
> +            "Description": "BIDS-compliant participant identifier.",
Maybe we could explicitly say that this should include the `sub-` prefix?

2024-12-20 15:13 UTC, michellewang commented on schemas/imaging_digest_schema.json
> +            "Description": "BIDS-compliant session identifier.",
Same comment as above but for `ses-` prefix

2024-12-20 15:13 UTC, michellewang commented on schemas/phenotypic_digest_schema.json
> +            "Description": "BIDS-compliant participant identifier.",
Same comment as for imaging bagel: maybe we could explicitly say that this should include the `sub-` prefix?

2024-12-20 15:13 UTC, michellewang commented on schemas/phenotypic_digest_schema.json
General question: is it on purpose that this file doesn't have `bids_session_id`? I guess that column is not very important since the pheno file cannot be used as input to other Neurobagel things

2025-01-07 22:08 UTC, surchs requested changes
Thanks @alyssadai. Changes look good, I did flag one thing I believe is an accidental change/bug with `pd.read_csv` to `pd.read_tsv`. I haven't tried this locally, but I'm pretty sure that doesn't work. Even if I'm wrong about that, I'd say add a test that covers the `load_file_from_path` route in `utility`, because it doesn't seem tested yet.

2025-01-07 22:08 UTC, surchs commented on digest/app.py
> +        "csv",  # NOTE: "tsv" is not an option for export_format
```suggestion
        "csv",  # NOTE: the dash_table.DataTable object does not support "tsv" as an option for export_format
```

2025-01-13 17:43 UTC, alyssadai commented on README.md
To be updated with correct paths from https://github.com/neurodatascience/qpn_workflows (1/2 of repos that have replaced https://github.com/neurodatascience/nipoppy-qpn) after @nikhil153 adds the latest imaging and phenotypic digest files.

2025-01-13 18:19 UTC, alyssadai commented on schemas/phenotypic_digest_schema.json
Good question. I omitted `bids_session_id` since I wouldn't expect that in phenotypic tabular data necessary, especially since in the context of Neurobagel phenotypic and imaging session labels do not need to match since they're treated separately (it's just the subject IDs that have this requirement).

That said, you're right that this file wouldn't really work as an input to Neurobagel tools as-is. To avoid confusion and allow for more flexibility, I've added `bids_session_id` as an optional column in this schema 🙂 . Let me know if you disagree!

2025-01-13 18:20 UTC, alyssadai commented
Blocked from merging until https://github.com/neurodatascience/qpn_workflows is updated with latest QPN digest files.

2025-01-15 15:47 UTC, surchs approved these changes
Great stuff @alyssadai :tada: 

:cook:

2025-01-15 15:47 UTC, surchs commented on schemas/imaging_digest_schema.json
> +            "description": "Version of the pipeline that was run.",
nice!

2025-01-16 05:01 UTC, merged